schema_version = "1.0.0"

id = "global_copy_nodes"
version = "1.0.5"
name = "Global Copy Nodes"
tagline = "Copy nodes across .blend projects"
maintainer = "hisprofile029@gmail.com"
type = "add-on"

website = "https://github.com/hisprofile/global_copy_nodes"

tags = ["System", "Node"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

 [permissions]
files = "Requires reading & writing node copy buffer to disk"